/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreerRouteImport } from './routes/creer'
import { Route as MSlugRouteImport } from './routes/m.$slug'
import { Route as ApiPublicImgRouteImport } from './routes/api.public.img'
import { Route as ApiPublicPdfSlugRouteImport } from './routes/api.public.pdf.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreerRoute = CreerRouteImport.update({
  id: '/creer',
  path: '/creer',
  getParentRoute: () => rootRouteImport,
} as any)
const MSlugRoute = MSlugRouteImport.update({
  id: '/m/$slug',
  path: '/m/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImgRoute = ApiPublicImgRouteImport.update({
  id: '/api/public/img',
  path: '/api/public/img',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPdfSlugRoute = ApiPublicPdfSlugRouteImport.update({
  id: '/api/public/pdf/$slug',
  path: '/api/public/pdf/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/creer': typeof CreerRoute
  '/m/$slug': typeof MSlugRoute
  '/api/public/img': typeof ApiPublicImgRoute
  '/api/public/pdf/$slug': typeof ApiPublicPdfSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/creer': typeof CreerRoute
  '/m/$slug': typeof MSlugRoute
  '/api/public/img': typeof ApiPublicImgRoute
  '/api/public/pdf/$slug': typeof ApiPublicPdfSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/creer': typeof CreerRoute
  '/m/$slug': typeof MSlugRoute
  '/api/public/img': typeof ApiPublicImgRoute
  '/api/public/pdf/$slug': typeof ApiPublicPdfSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/creer' | '/m/$slug' | '/api/public/img' | '/api/public/pdf/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/creer' | '/m/$slug' | '/api/public/img' | '/api/public/pdf/$slug'
  id:
    | '__root__'
    | '/'
    | '/creer'
    | '/m/$slug'
    | '/api/public/img'
    | '/api/public/pdf/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreerRoute: typeof CreerRoute
  MSlugRoute: typeof MSlugRoute
  ApiPublicImgRoute: typeof ApiPublicImgRoute
  ApiPublicPdfSlugRoute: typeof ApiPublicPdfSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creer': {
      id: '/creer'
      path: '/creer'
      fullPath: '/creer'
      preLoaderRoute: typeof CreerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$slug': {
      id: '/m/$slug'
      path: '/m/$slug'
      fullPath: '/m/$slug'
      preLoaderRoute: typeof MSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/img': {
      id: '/api/public/img'
      path: '/api/public/img'
      fullPath: '/api/public/img'
      preLoaderRoute: typeof ApiPublicImgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pdf/$slug': {
      id: '/api/public/pdf/$slug'
      path: '/api/public/pdf/$slug'
      fullPath: '/api/public/pdf/$slug'
      preLoaderRoute: typeof ApiPublicPdfSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreerRoute: CreerRoute,
  MSlugRoute: MSlugRoute,
  ApiPublicImgRoute: ApiPublicImgRoute,
  ApiPublicPdfSlugRoute: ApiPublicPdfSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
